In [10]:
import re
import numpy as np

def parse_array(string):
    return [int(x) for x in re.findall(r'\d+', string)]

file_path = r"C:\Users\prave\Downloads\HW 3\Prob 4\final\final_matches.txt"

final_matches = []

with open(file_path, 'r') as file:
    for line in file:
        match_strings = line.strip().split('), ')
        match = (parse_array(match_strings[0]), parse_array(match_strings[1]))
        final_matches.append(match)


In [12]:
Points1 = [(final_matches[i][0][0],final_matches[i][0][1]) for i in range(len(final_matches))]
Points2 = [(final_matches[i][1][0],final_matches[i][1][1]) for i in range(len(final_matches))]


In [52]:
A = np.zeros((2 * len(Points1),6))
b = np.zeros(2 * len(Points2) )

j=1
for i in range(0,len(Points1)):
    A[2*i, :] = [Points1[i][0], Points1[i][1], 1, 0, 0, 0]
    A[j, :] = [0, 0, 0, Points1[i][0], Points1[i][1], 1]
    
    b[2*i] = Points2[i][0]
    
    b[j ] = Points2[i][1]
    
    j=j+2
      
   

In [53]:
A = A[:80, :]
b = b[:80]

In [54]:
np.dot(np.dot(np.linalg.inv(np.dot(A.T, A)),A.T),b) 

array([  0.74616578,   0.65723616,  30.8418054 ,  -0.64980054,
         0.72385415, 188.47314306])

In [49]:
A

array([[198., 148.,   1.,   0.,   0.,   0.],
       [  0.,   0.,   0., 198., 148.,   1.],
       [198., 149.,   1.,   0.,   0.,   0.],
       [  0.,   0.,   0., 198., 149.,   1.],
       [103., 143.,   1.,   0.,   0.,   0.],
       [  0.,   0.,   0., 103., 143.,   1.],
       [ 94., 145.,   1.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  94., 145.,   1.],
       [189., 150.,   1.,   0.,   0.,   0.],
       [  0.,   0.,   0., 189., 150.,   1.],
       [131., 110.,   1.,   0.,   0.,   0.],
       [  0.,   0.,   0., 131., 110.,   1.],
       [174., 195.,   1.,   0.,   0.,   0.],
       [  0.,   0.,   0., 174., 195.,   1.],
       [ 99., 145.,   1.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  99., 145.,   1.],
       [197., 146.,   1.,   0.,   0.,   0.],
       [  0.,   0.,   0., 197., 146.,   1.],
       [175., 197.,   1.,   0.,   0.,   0.],
       [  0.,   0.,   0., 175., 197.,   1.],
       [101., 144.,   1.,   0.,   0.,   0.],
       [  0.,   0.,   0., 101., 144.,   1.],
       [19

In [27]:
b

array([273., 170., 273., 170., 200., 229., 198., 230., 273., 170., 203.,
       181., 290., 219., 198., 230., 273., 170., 290., 219., 200., 229.,
       273., 170., 273., 170., 290., 219., 203., 181., 273., 170., 273.,
       170., 273., 170., 198., 230., 273., 170., 273., 170., 273., 170.,
       273., 170., 273., 170., 273., 170.])